version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: cron
      cronjob: 0 7 * * 1-5
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: cron
      cronjob: 0 7 * * 1-5
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: cron
      cronjob: 0 7 * * 1-5
    allow:
      - dependency-type: "all"
